### ISSUE TITLE
Add paper's link

### ISSUE THREAD

**Issue by 943fansi** [OrigamiSL/GBT#1]
@OrigamiSL. Thanks for your great work. Could you please add the link of pdf?

**Comment by 943fansi** [comment]
@OrigamiSL. Thank you very much for your work on time series forecasting. I have added several of your code repositories and put them here[Time-Series-Forecasting-and-Deep-Learning](https://github.com/DaoSword/Time-Series-Forecasting-and-Deep-Learning/issues/3). It is a pity that some pdf links are missing. Can you upload to the arxiv website and add accessible links?

**Comment by OrigamiSL** [comment]
Thanks for your interests. It is a pity that journal this paper is submitted to does not allow any format of preprint. However, we will surely supplement it once the paper is accepted or is re-submitted to other journals allowing preprints.
