### ISSUE TITLE
why

### ISSUE THREAD

**Issue by loveciel** [OrigamiSL/GBT#3]
Hello and thank you for your contribution. But I have a question: how does the GPT in the code here combine with the other Transformer

**Comment by OrigamiSL** [comment]
You may refer to the commands, e.g., --model, in main.py and Line 29 - Line 202 in exp_model.py  to know the usages of the other models (Transformers) which are merged into this resposity. It would be easier if you are familiar with these models, e.g., FEDformer. Indeed, you can manually test more recent Transformers with GBT, e.g., PatchTST. But be aware that the usage of GBT contradicts the prevailing RevIN, which is employed in some recent works.
