### ISSUE TITLE
MS问题

### ISSUE THREAD

**Issue by dairuo678** [OrigamiSL/GBT#4]
您好，我用GBT模型跑MS预测，发现预测结果过大，请问是什么问题
![image](https://github.com/OrigamiSL/GBT-Neural_Networks_2023/assets/134246309/8dd579d7-cb1a-4a69-9a26-4127634fb1ad)

**Comment by OrigamiSL** [comment]
MS没意义不用跑

**Comment by dairuo678** [comment]
好的，谢谢

**Comment by dairuo678** [comment]
您好，我有点疑惑，就是pred_len设置的96 192 336 720之间有什么联系呢，还是就是按照想要预测的数据时间长度来设置的呢？

**Comment by OrigamiSL** [comment]
这个是大部分其他论文的设定，较早用的是Autoformer(2021)模型，以及后续的几乎所有实验模型都是这么设的，没有太具体的原因。我个人理解是都是24的倍数，因为大部分数据集是以1小时为采样间隔的，将预测长度设为天数的整数倍较为合理。

**Comment by loveciel** [comment]
> MS没意义不用跑

为什么没有意义呀
