### ISSUE TITLE
instance parameter

### ISSUE THREAD

**Issue by feng-weiguo** [OrigamiSL/GBT#5]
作者你好，我在代码中看到instance为True时，最后一个维度reshape为1，可以解释下这个作用吗，谢谢。

**Comment by OrigamiSL** [comment]
来自TS2Vec的instance forecasting模式，这在论文里已经交代了。简单来说，不对变量或者时间维度进行embedding，而是选择创造一个新的维度，也是就1，来进行embedding和特征提取。详细请自己阅读相关文献。
